# Generated by Django 4.2.11 on 2024-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/noimage.png', upload_to='uploads', verbose_name='プロフィール画像'),
        ),
    ]
