# Generated by Django 4.2.11 on 2024-05-14 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('from_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_name', to=settings.AUTH_USER_MODEL)),
                ('to_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
