# Generated by Django 4.2.11 on 2024-05-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_talk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='from_name',
            new_name='talk_from',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='to_name',
            new_name='talk_to',
        ),
    ]
